### PR TITLE
Create economy.js again, then I’ll create config/color in another

### PR DESCRIPTION
**Pull request by BaneOfAll**

### CODE REVIEW

**Comment by BaneOfAll** [comment]
Wait there is config/color. Why didn’t it work before? Please look at it before reverting/merging

**Comment by Spandamn** [comment]
There is seriously no need of this

**Comment by Spandamn** [comment]
We're trying to stick to the original Zarel repo to minimize the number of crashes

**Comment by Spandamn** [comment]
guess ill close this

**Pull request closed without merging**
